Correction libretti Les Bavards d'Offenbach
Chartes-TNAH/libretti pull request #21
Opened 2020-03-06 14:44 UTC by jeandamien-genero

Ed,

Voici mon dépôt pour le projet libretti, sur _Les Bavards_ de Jacques Offenbach, pour correction.

2020-03-08 20:43 UTC, egray523 commented
Cher Jean-Damien,

Merci pour ta pull-request. Cependant, il faut que tu corriges le `<ti:titre>` dans le metadata file __cts__.xml pour l'oeuvre - il est maintenant occupé par le texte placeholder "titre de l'opéra."

à part de celui-là, tout me parait bon.

2020-03-16 13:43 UTC, egray523 requested changes
Tout me parait bon, il reste la coquille sur le `   <ti:title xml:lang="fre">titre de l'opéra</ti:title>` dans le fichier __cts__.xml au niveau de l'oeuvre. 

Aussi, il y va avoir un conflit au niveau de ton __cts__.xml pour Offenbach parce que tu as toujours le déclaration `<?xml version="1.0" encoding="UTF-8"?>` mais ça peut etre résolu au moment du merge par moi. Lors de notre dernière discussion, on a décidé que les déclarations étaient facultatives, et comme le premier qui est arrivé pour Offenbach a décidé de ne pas en avoir une, il n'y a pas pour Offenbach. Tu peux quand même garder celui sur le __cts__.xml pour l'oeuvre, comme c'est facultative. Comme tu veux! 

(Je sais que tu est déjà au courant du problème pour le titre, mais je pensais qu'il vaudra mieux faire "request changes" pour utiliser tous les outils proposé par nos amis à Github.

2020-03-20 11:07 UTC, jeandamien-genero commented
OK, merci. C'est fait, est-ce que tout te parait bon maintenant ?

2020-03-20 14:03 UTC, egray523 approved these changes

2020-03-20 14:08 UTC, merged